name = "pan-deploy"
main = "src/worker.ts"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "settings", id = "96ac18647f5843e1aa43efd965191645" }
]
